<?php
namespace Database\Seeders;
use App\Models\Admin; use App\Models\Appointment; use App\Models\Client; use App\Models\CompanySetting; use App\Models\Message; use App\Models\Portfolio; use App\Models\TeamMember;
use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder { public function run(): void {
Admin::updateOrCreate(['email'=>'admin@ksn.co.id'],['name'=>'Administrator','password'=>Hash::make('admin123')]);
$portfolios=[
['title'=>'Residensi Harmoni','client'=>'Dr. Andi & Family','category'=>'Interior • Minimalis','year'=>2023,'location'=>'Jakarta Selatan','area'=>'280 m²','description'=>'Transformasi total hunian 280 m² menjadi ruang minimalis modern yang lapang dan terang. Menggunakan material kayu oak, marmer travertine, dan palet warna netral dengan aksen hitam.','image'=>'https://picsum.photos/seed/residence-harmoni/900/500'],
['title'=>'Tower Nusantara','client'=>'PT Nusantara Development','category'=>'Gedung • Modern','year'=>2022,'location'=>'Jakarta Pusat','area'=>'25.000 m²','description'=>'Gedung perkantoran 20 lantai dengan fasad double-skin glass curtain wall untuk efisiensi energi. Interior lobby premium dengan ceiling tinggi 12 meter.','image'=>'https://picsum.photos/seed/tower-office/900/500'],
['title'=>'Hotel Grand Nusantara','client'=>'Grand Nusantara Group','category'=>'Interior • Luxury Classic','year'=>2023,'location'=>'Bali','area'=>'15.000 m²','description'=>'Desain interior 120 kamar, lobby, 3 restoran, spa, dan ballroom dengan tema luxury classic Bali modern.','image'=>'https://picsum.photos/seed/hotel-lobby-lux/900/500'],
['title'=>'Kantor Pusat Maju Bersama','client'=>'PT Maju Bersama','category'=>'Gedung • Industrial','year'=>2021,'location'=>'Surabaya','area'=>'8.500 m²','description'=>'Kantor pusat bergaya industrial modern dengan beton ekspos, struktur baja terlihat, dan open-plan workspace.','image'=>'https://picsum.photos/seed/office-modern-arch/900/500'],
['title'=>'Villa Pantai Indah','client'=>'Mr. & Mrs. Tanaka','category'=>'Renovasi • Tropical','year'=>2022,'location'=>'Lombok','area'=>'450 m²','description'=>'Renovasi total villa pantai dengan infinity pool, rooftop lounge, dan elemen tropical nusantara modern.','image'=>'https://picsum.photos/seed/villa-renovated/900/500'],
['title'=>'Taman Kota Hijau','client'=>'Pemerintah Kota Bandung','category'=>'Landscape • Eco-Friendly','year'=>2023,'location'=>'Bandung','area'=>'3.2 Hektar','description'=>'Masterplan taman kota dengan harvesting air hujan, solar-powered lighting, dan amphitheater.','image'=>'https://picsum.photos/seed/park-garden-design/900/500'],
['title'=>'Apartemen Nordik Residence','client'=>'Ms. Sarah Putri','category'=>'Interior • Skandinavia','year'=>2024,'location'=>'Jakarta Barat','area'=>'120 m²','description'=>'Desain interior apartemen bergaya Skandinavia dengan furniture custom kayu birch dan tekstil linen.','image'=>'https://picsum.photos/seed/apartment-scandi/900/500'],
['title'=>'Sekolah Cerdas Bangsa','client'=>'Yayasan Cerdas Bangsa','category'=>'Gedung • Green Building','year'=>2024,'location'=>'Yogyakarta','area'=>'12.000 m²','description'=>'Sekolah green building dengan solar panel, natural ventilation, dan vertical garden.','image'=>'https://picsum.photos/seed/school-building-new/900/500'],
['title'=>'Restorasi Gedung Heritage','client'=>'Dinas Kebudayaan Jateng','category'=>'Renovasi • Heritage','year'=>2021,'location'=>'Semarang','area'=>'2.800 m²','description'=>'Restorasi bangunan cagar budaya era kolonial menjadi museum modern.','image'=>'https://picsum.photos/seed/heritage-restored/900/500']];
foreach($portfolios as $p) Portfolio::updateOrCreate(['title'=>$p['title']],$p);
$appointments=[['name'=>'Hendra Wijaya','phone'=>'+62 812-1111-2222','email'=>'hendra@company.com','type'=>'Konsultasi Proyek','date'=>'2026-09-02','time'=>'10:00','status'=>'confirmed'],['name'=>'Diana Kusuma','phone'=>'+62 813-2222-3333','email'=>'diana@email.com','type'=>'Review Desain','date'=>'2026-09-03','time'=>'14:00','status'=>'pending']]; foreach($appointments as $a) Appointment::updateOrCreate(['email'=>$a['email'],'date'=>$a['date'],'time'=>$a['time']],$a);
$clients=[['name'=>'PT Nusantara Development','pic'=>'Hendra Wijaya','phone'=>'(021) 555-0101','email'=>'info@nusantara.co.id','projects'=>3,'total'=>'Rp 68 M'],['name'=>'Dr. Andi Family','pic'=>'Dr. Andi','phone'=>'(021) 555-0202','email'=>'andi@email.com','projects'=>1,'total'=>'Rp 2.8 M'],['name'=>'Grand Nusantara Group','pic'=>'Rizal Pratama','phone'=>'(0361) 555-0303','email'=>'info@grandnusantara.com','projects'=>2,'total'=>'Rp 23 M'],['name'=>'Mr. Tanaka','pic'=>'Mr. Tanaka','phone'=>'+62 812-555-0404','email'=>'tanaka@email.com','projects'=>1,'total'=>'Rp 8.5 M'],['name'=>'Yayasan Cerdas Bangsa','pic'=>'Siti Aminah','phone'=>'(0274) 555-0505','email'=>'info@cerdasbangsa.org','projects'=>1,'total'=>'Rp 28 M']]; foreach($clients as $c) Client::updateOrCreate(['name'=>$c['name']],$c);
$messages=[['name'=>'Sari Dewi','email'=>'sari@email.com','subject'=>'Pertanyaan desain interior','msg'=>'Halo, saya ingin bertanya tentang jasa desain interior untuk rumah di BSD. Bisakah konsultasi gratis?','is_read'=>false],['name'=>'Bambang S.','email'=>'bambang@corp.id','subject'=>'Request penawaran gedung perkantoran','msg'=>'Kami membutuhkan penawaran untuk gedung 8 lantai di Sudirman. Luas tanah 500m2.','is_read'=>false]]; foreach($messages as $m) Message::firstOrCreate(['email'=>$m['email'],'subject'=>$m['subject']],$m);
$team=[['name'=>'Ir. Budi Santoso, M.T.','role'=>'Direktur Utama','email'=>'budi@ksn.co.id','phone'=>'+62 811-000-0001','img'=>'https://picsum.photos/seed/director-man/100/100'],['name'=>'Ar. Siti Rahayu, S.T.','role'=>'Lead Architect','email'=>'siti@ksn.co.id','phone'=>'+62 812-000-0002','img'=>'https://picsum.photos/seed/architect-woman/100/100'],['name'=>'Ir. Ahmad Fauzi, S.E.','role'=>'Structural Engineer','email'=>'ahmad@ksn.co.id','phone'=>'+62 813-000-0003','img'=>'https://picsum.photos/seed/engineer-guy/100/100'],['name'=>'Dian Permata, S.Ds.','role'=>'Interior Designer','email'=>'dian@ksn.co.id','phone'=>'+62 814-000-0004','img'=>'https://picsum.photos/seed/designer-lady/100/100'],['name'=>'Riko Maulana, S.T.','role'=>'Site Manager','email'=>'riko@ksn.co.id','phone'=>'+62 815-000-0005','img'=>'https://picsum.photos/seed/construction-worker/100/100']]; foreach($team as $t) TeamMember::updateOrCreate(['email'=>$t['email']],$t);
CompanySetting::firstOrCreate([],['company'=>'PT Karya Struktur Nusantara','address'=>'Jl. Sudirman Kav. 52-53, Lantai 15, Jakarta Selatan 12190','phone'=>'(021) 1234-567','email'=>'info@ksn-konstruksi.co.id','whatsapp'=>'+62 812-3456-7890']);
} }
